### PR TITLE
change fullname to name

### PR DESCRIPTION
**Pull request by ezhasyafaat**
## Description
Change key fullname on scheme/user.json to name

## Related Issue

I found some error when i was try to create user from API, its because in scheme/user.json use key "fullname", but in model search for column "name"

### CODE REVIEW

**Comment by mychidarko** [comment]
@ezhasyafaat I'll check out the issue if it still stands

**Comment by ezhasyafaat** [comment]
okay, in my local project i have fixed this issue, but i close the PR because i have PR to master

**Comment by ezhasyafaat** [comment]
can you check this again @mychidarko?

**Comment by mychidarko** [comment]
Hey @ezhasyafaat finally got the chance to look through the issue. Actually both schema and migrations use `fullname`, so those can be left unchanged. The only change needed here is on the `User` model. You can edit the `$fillable` field to fullname there.

Like this:

```php
protected $fillable = [
    'fullname', 'email', 'password',
];
```

**Review by mychidarko — COMMENTED** [review]
Hey @ezhasyafaat finally got the chance to look through the issue. Actually both schema and migrations use `fullname`, so those can be left unchanged. The only change needed here is on the `User` model. You can edit the `$fillable` field to fullname there.

Like this:

```php
protected $fillable = [
    'fullname', 'email', 'password',
];
```

**Comment by ezhasyafaat** [comment]
in my local project i try to just change the model user, but i found error again `Leaf\Exceptions\ErrorException: SQLSTATE[42S22]: Column not found: 1054 Unknown column &#039;name& (truncated...)  `

**Comment by ezhasyafaat** [comment]
so i think we have to change scaffold auth in repo aloe, what do you think? @mychidarko

**Comment by mychidarko** [comment]
What do you have in mind?

**Comment by ezhasyafaat** [comment]
In ApiAuth/controller/Auth/RegisterController.php, weh have to change 
```php
$credentials = request()->get(['username', 'name', 'email', 'password']);

        $validation = Form::validate([
            'name' => 'required',
            'username' => ['username', 'max:15'],
            'email' => 'email',
            'password' => 'min:8'
        ]);
 ```
 
 to
 
 ```php
 $credentials = request()->get(['username', 'fullname', 'email', 'password']);

        $validation = Form::validate([
            'fullname' => 'required',
            'username' => ['username', 'max:15'],
            'email' => 'email',
            'password' => 'min:8'
        ]);
```

**Comment by ezhasyafaat** [comment]
i can do it this in this repo
```php
protected $fillable = [
    'fullname', 'email', 'password',
];
```
and i can do it this in aloe repo
```php
$credentials = request()->get(['username', 'fullname', 'email', 'password']);

$validation = Form::validate([
   'fullname' => 'required',
   'username' => ['username', 'max:15'],
   'email' => 'email',
   'password' => 'min:8'
]);
```

**Comment by mychidarko** [comment]
Oh yeah, right. In the controller as well

**Comment by ezhasyafaat** [comment]
okay i will fix it now

**Review by mychidarko — APPROVED** [review]

**Pull request merged**
